repos:
- repo: meta
  hooks:
  -  id: check-hooks-apply
  -  id: check-useless-excludes

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.0
  hooks:
  -  id: black
     language_version: python3
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  -  id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -  id: trailing-whitespace
  -  id: end-of-file-fixer
  -  id: fix-byte-order-marker
  -  id: check-merge-conflict
  -  id: check-case-conflict
  -  id: check-xml
  -  id: check-yaml
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  -  id: flake8
     additional_dependencies:
     - flake8-absolute-import
     - flake8-black
